name: Build Surge Rules

on:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: |
          echo "CHINA_URL=https://raw.githubusercontent.com/pmkol/easymosdns/rules/china_domain_list.txt" >> $GITHUB_ENV
          echo "GFW_URL=https://raw.githubusercontent.com/pmkol/easymosdns/rules/gfw_domain_list.txt" >> $GITHUB_ENV
          echo "AD_URL=https://raw.githubusercontent.com/pmkol/easymosdns/refs/heads/rules/ad_domain_list.txt" >> $GITHUB_ENV

      - name: Convert china domains
        run: |
          curl -sSL $CHINA_URL \
            | grep -v '^\s*#' | grep -v '^\s*$' \
            | sed 's/^/DOMAIN-SUFFIX,/' \
            > china.list

      - name: Convert gfw domains
        run: |
          curl -sSL $GFW_URL \
            | grep -v '^\s*#' | grep -v '^\s*$' \
            | sed 's/^/DOMAIN-SUFFIX,/' \
            > gfw.list

      - name: Convert ad domains
        run: |
          curl -sSL $AD_URL \
            | grep -v '^\s*#' | grep -v '^\s*$' \
            | sed 's/^domain:/DOMAIN-SUFFIX,/' \
            > reject.list

      - name: Push to release branch
        run: |
          mkdir output && mv china.list gfw.list reject.list output/
          cd output
          git init
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b release
          git add .
          git commit -m "Updated $(TZ=Asia/Shanghai date +'%Y-%m-%d %H:%M')"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin release
